services:
  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    volumes:
      - ~/models:/models
      - ollama_data:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped

  discord-quotes-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama
    environment:
      PORT: 3000
      OLLAMA_HOST: "http://ollama:11434"
    ports:
      - 3000:3000
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  ollama_data:
